-- MySQL Script generated by MySQL Workbench
-- qua 20 mar 2019 12:07:19 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema devUpload
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema devUpload
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devUpload` DEFAULT CHARACTER SET utf8 ;
USE `devUpload` ;

-- -----------------------------------------------------
-- Table `devUpload`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devUpload`.`Usuarios` (
  `userId` INT(3) NOT NULL AUTO_INCREMENT,
  `userNome` VARCHAR(45) NOT NULL,
  `userNickName` VARCHAR(60) NOT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `userSenha` VARCHAR(45) NOT NULL,
  `userFoto` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devUpload`.`Pastas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devUpload`.`Pastas` (
  `pastId` INT(3) NOT NULL AUTO_INCREMENT,
  `pastNome` VARCHAR(45) NOT NULL,
  `fk_userPast` INT(3) NOT NULL,
  INDEX `fk_Pastas_Usuarios1_idx` (`fk_userPast` ASC),
  PRIMARY KEY (`pastId`),
  CONSTRAINT `fk_Pastas_Usuarios`
    FOREIGN KEY (`fk_userPast`)
    REFERENCES `devUpload`.`Usuarios` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devUpload`.`Conteudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devUpload`.`Conteudos` (
  `contId` INT(3) NOT NULL AUTO_INCREMENT,
  `contNome` VARCHAR(45) NOT NULL,
  `fk_pastCont` INT(3) NOT NULL,
  PRIMARY KEY (`contId`),
  INDEX `fk_Conteudos_Pastas1_idx` (`fk_pastCont` ASC),
  CONSTRAINT `fk_Conteudos_Pastas1`
    FOREIGN KEY (`fk_pastCont`)
    REFERENCES `devUpload`.`Pastas` (`pastId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `devUpload` ;

-- -----------------------------------------------------
-- Placeholder table for view `devUpload`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devUpload`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `devUpload`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devUpload`.`view1`;
USE `devUpload`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
