-- MySQL Script generated by MySQL Workbench
-- ter 04 jun 2019 19:41:17 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema devPHP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema devPHP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devPHP` DEFAULT CHARACTER SET utf8 ;
USE `devPHP` ;

-- -----------------------------------------------------
-- Table `devPHP`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devPHP`.`Estados` (
  `estadId` INT NOT NULL,
  `estadNome` VARCHAR(45) NOT NULL,
  `estadSigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`estadId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devPHP`.`Cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devPHP`.`Cidades` (
  `cidId` INT NOT NULL,
  `cidNome` VARCHAR(45) NOT NULL,
  `Estados_estadId` INT NOT NULL,
  PRIMARY KEY (`cidId`),
  INDEX `fk_Cidades_Estados_idx` (`Estados_estadId` ASC),
  CONSTRAINT `fk_Cidades_Estados`
    FOREIGN KEY (`Estados_estadId`)
    REFERENCES `devPHP`.`Estados` (`estadId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devPHP`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devPHP`.`Usuarios` (
  `userNome` VARCHAR(45) NOT NULL,
  `userCpf` INT(11) NOT NULL,
  `userDtNascimento` DATE NOT NULL,
  `userEmail` VARCHAR(60) NOT NULL,
  `userTelefone` CHAR(11) NOT NULL,
  `userEndereco` VARCHAR(45) NOT NULL,
  `Cidades_cidId` INT NOT NULL,
  PRIMARY KEY (`userCpf`),
  INDEX `fk_Usuarios_Cidades1_idx` (`Cidades_cidId` ASC),
  CONSTRAINT `fk_Usuarios_Cidades1`
    FOREIGN KEY (`Cidades_cidId`)
    REFERENCES `devPHP`.`Cidades` (`cidId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
